[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "labctl"
version = '0.0.2'
requires-python = ">=3.10"
dependencies = [
    "numpy",
    "scipy",
    "typing-extensions",
]

authors = [
    {name = "Martijn Ruijzendaal", email = "martijn.ruijzendaal@gmail.com"},
    {name = "Thijs Drost", email = "thijs.drost@maastrichtuniversity.nl"}
]

[project.urls]
repository = "https://github.com/Brightsite-Plasmalab"

[tool.setuptools.packages.find]
where = ["src"]

[dependency-groups]
analysis = [
    "matplotlib>=3.10.9",
    "sif-parser>=0.3.6",
]
dev = [
    "pytest>=9.0.3",
    "pytest-cov>=7.1.0",
    "pyrefly>=0.60.0",
]

[tool.pytest.ini_options]
addopts = [
    "--import-mode=importlib",
    "--cov=labctl",
    "--cov-branch",
    "--cov-report=term-missing",
]
testpaths = [
    "tests"
]

[tool.pyrefly]
preset = "default"