# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'minimale_widget_stepper_multi.ui'
#
# Created by: PyQt5 UI code generator 5.14.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(461, 633)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.groupBox_3 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_3.setObjectName("groupBox_3")
        self.formLayout = QtWidgets.QFormLayout(self.groupBox_3)
        self.formLayout.setObjectName("formLayout")
        self.label = QtWidgets.QLabel(self.groupBox_3)
        self.label.setObjectName("label")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.port_cB = QtWidgets.QComboBox(self.groupBox_3)
        self.port_cB.setObjectName("port_cB")
        self.horizontalLayout_4.addWidget(self.port_cB)
        self.baudrate_cB = QtWidgets.QComboBox(self.groupBox_3)
        self.baudrate_cB.setObjectName("baudrate_cB")
        self.baudrate_cB.addItem("")
        self.baudrate_cB.addItem("")
        self.baudrate_cB.addItem("")
        self.horizontalLayout_4.addWidget(self.baudrate_cB)
        self.init_btn = QtWidgets.QPushButton(self.groupBox_3)
        self.init_btn.setObjectName("init_btn")
        self.horizontalLayout_4.addWidget(self.init_btn)
        self.formLayout.setLayout(0, QtWidgets.QFormLayout.FieldRole, self.horizontalLayout_4)
        self.label_2 = QtWidgets.QLabel(self.groupBox_3)
        self.label_2.setObjectName("label_2")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_2)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.port_cB_stage = QtWidgets.QComboBox(self.groupBox_3)
        self.port_cB_stage.setObjectName("port_cB_stage")
        self.horizontalLayout_6.addWidget(self.port_cB_stage)
        self.baudrate_cB_stage = QtWidgets.QComboBox(self.groupBox_3)
        self.baudrate_cB_stage.setObjectName("baudrate_cB_stage")
        self.baudrate_cB_stage.addItem("")
        self.baudrate_cB_stage.addItem("")
        self.baudrate_cB_stage.addItem("")
        self.baudrate_cB_stage.addItem("")
        self.horizontalLayout_6.addWidget(self.baudrate_cB_stage)
        self.init_btn_stage = QtWidgets.QPushButton(self.groupBox_3)
        self.init_btn_stage.setObjectName("init_btn_stage")
        self.horizontalLayout_6.addWidget(self.init_btn_stage)
        self.formLayout.setLayout(1, QtWidgets.QFormLayout.FieldRole, self.horizontalLayout_6)
        self.update_list_btn = QtWidgets.QPushButton(self.groupBox_3)
        self.update_list_btn.setObjectName("update_list_btn")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.SpanningRole, self.update_list_btn)
        self.verticalLayout.addWidget(self.groupBox_3)
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setObjectName("groupBox")
        self.gridLayout = QtWidgets.QGridLayout(self.groupBox)
        self.gridLayout.setObjectName("gridLayout")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_9 = QtWidgets.QLabel(self.groupBox)
        self.label_9.setObjectName("label_9")
        self.horizontalLayout_2.addWidget(self.label_9)
        self.cmdPath_lE = QtWidgets.QLineEdit(self.groupBox)
        self.cmdPath_lE.setObjectName("cmdPath_lE")
        self.horizontalLayout_2.addWidget(self.cmdPath_lE)
        self.execBNC_btn = QtWidgets.QPushButton(self.groupBox)
        self.execBNC_btn.setEnabled(False)
        self.execBNC_btn.setObjectName("execBNC_btn")
        self.horizontalLayout_2.addWidget(self.execBNC_btn)
        self.gridLayout.addLayout(self.horizontalLayout_2, 0, 0, 1, 1)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_11 = QtWidgets.QLabel(self.groupBox)
        self.label_11.setObjectName("label_11")
        self.horizontalLayout_3.addWidget(self.label_11)
        spacerItem = QtWidgets.QSpacerItem(244, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem)
        self.gridLayout.addLayout(self.horizontalLayout_3, 1, 0, 1, 1)
        self.log_TE = QtWidgets.QTextEdit(self.groupBox)
        self.log_TE.setObjectName("log_TE")
        self.gridLayout.addWidget(self.log_TE, 2, 0, 1, 1)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_7 = QtWidgets.QLabel(self.groupBox)
        self.label_7.setObjectName("label_7")
        self.horizontalLayout.addWidget(self.label_7)
        self.horizontalLayout_12 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        self.cmd_le_stage = QtWidgets.QLineEdit(self.groupBox)
        self.cmd_le_stage.setObjectName("cmd_le_stage")
        self.horizontalLayout_12.addWidget(self.cmd_le_stage)
        self.send_btn_stage = QtWidgets.QPushButton(self.groupBox)
        self.send_btn_stage.setEnabled(False)
        self.send_btn_stage.setObjectName("send_btn_stage")
        self.horizontalLayout_12.addWidget(self.send_btn_stage)
        self.horizontalLayout.addLayout(self.horizontalLayout_12)
        self.gridLayout.addLayout(self.horizontalLayout, 3, 0, 1, 1)
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.label_6 = QtWidgets.QLabel(self.groupBox)
        self.label_6.setObjectName("label_6")
        self.horizontalLayout_9.addWidget(self.label_6)
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.cmd_le = QtWidgets.QLineEdit(self.groupBox)
        self.cmd_le.setObjectName("cmd_le")
        self.horizontalLayout_10.addWidget(self.cmd_le)
        self.send_btn = QtWidgets.QPushButton(self.groupBox)
        self.send_btn.setEnabled(False)
        self.send_btn.setObjectName("send_btn")
        self.horizontalLayout_10.addWidget(self.send_btn)
        self.horizontalLayout_9.addLayout(self.horizontalLayout_10)
        self.gridLayout.addLayout(self.horizontalLayout_9, 4, 0, 1, 1)
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.stop_btn = QtWidgets.QPushButton(self.groupBox)
        self.stop_btn.setEnabled(False)
        self.stop_btn.setObjectName("stop_btn")
        self.horizontalLayout_11.addWidget(self.stop_btn)
        self.move_btn = QtWidgets.QPushButton(self.groupBox)
        self.move_btn.setEnabled(False)
        self.move_btn.setObjectName("move_btn")
        self.horizontalLayout_11.addWidget(self.move_btn)
        self.gridLayout.addLayout(self.horizontalLayout_11, 5, 0, 1, 1)
        self.verticalLayout.addWidget(self.groupBox)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 461, 22))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        self.menuHelp = QtWidgets.QMenu(self.menubar)
        self.menuHelp.setObjectName("menuHelp")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionAbout = QtWidgets.QAction(MainWindow)
        self.actionAbout.setObjectName("actionAbout")
        self.actionLoad_config = QtWidgets.QAction(MainWindow)
        self.actionLoad_config.setObjectName("actionLoad_config")
        self.actionExit = QtWidgets.QAction(MainWindow)
        self.actionExit.setObjectName("actionExit")
        self.menuFile.addAction(self.actionLoad_config)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionExit)
        self.menuHelp.addAction(self.actionAbout)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuHelp.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Auto Lab"))
        self.groupBox_3.setTitle(_translate("MainWindow", "Communication management"))
        self.label.setText(_translate("MainWindow", "Serial connection BNC:"))
        self.baudrate_cB.setCurrentText(_translate("MainWindow", "38400"))
        self.baudrate_cB.setItemText(0, _translate("MainWindow", "38400"))
        self.baudrate_cB.setItemText(1, _translate("MainWindow", "9600"))
        self.baudrate_cB.setItemText(2, _translate("MainWindow", "115200"))
        self.init_btn.setText(_translate("MainWindow", "Initialize"))
        self.label_2.setText(_translate("MainWindow", "Serial connection stage:"))
        self.baudrate_cB_stage.setCurrentText(_translate("MainWindow", "9600"))
        self.baudrate_cB_stage.setItemText(0, _translate("MainWindow", "9600"))
        self.baudrate_cB_stage.setItemText(1, _translate("MainWindow", "19200"))
        self.baudrate_cB_stage.setItemText(2, _translate("MainWindow", "38400"))
        self.baudrate_cB_stage.setItemText(3, _translate("MainWindow", "115200"))
        self.init_btn_stage.setText(_translate("MainWindow", "Initialize"))
        self.update_list_btn.setText(_translate("MainWindow", "Update lists"))
        self.groupBox.setTitle(_translate("MainWindow", "Commands and log"))
        self.label_9.setText(_translate("MainWindow", "Script file"))
        self.execBNC_btn.setText(_translate("MainWindow", "Execute commands in the file"))
        self.label_11.setText(_translate("MainWindow", "Serial monitor + log"))
        self.label_7.setText(_translate("MainWindow", "Custom instruction:"))
        self.send_btn_stage.setText(_translate("MainWindow", "Send to stage"))
        self.label_6.setText(_translate("MainWindow", "Custom instruction:"))
        self.send_btn.setText(_translate("MainWindow", "Send to BNC"))
        self.stop_btn.setText(_translate("MainWindow", "Stop"))
        self.move_btn.setText(_translate("MainWindow", "Start"))
        self.menuFile.setTitle(_translate("MainWindow", "File"))
        self.menuHelp.setTitle(_translate("MainWindow", "Help"))
        self.actionAbout.setText(_translate("MainWindow", "About"))
        self.actionLoad_config.setText(_translate("MainWindow", "Load config"))
        self.actionExit.setText(_translate("MainWindow", "Exit"))
